spring.application.name=Spring
server.port=8081

spring.thymeleaf.cache=false

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sunh
spring.datasource.username=root
spring.datasource.password=0116

mybatis.mapper-locations=mappers/*Mapper.xml